nelmio_cors:
    defaults:
        allow_origin: ['*']
        allow_credentials: false
        allow_headers: ['Content-Type', 'Authorization', 'Turbo-Frame']
        expose_headers: []
        allow_methods: ['GET', 'OPTIONS']
        max_age: 3600
    paths:
        '^/service': ~
