security:
    password_hashers:
        App\Entity\User:
            algorithm: sodium
            migrate_from:
                - bcrypt
                - legacy
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
            algorithm: 'auto'
            cost: 15

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        main:
            lazy: true
            provider: app_user_provider
            custom_authenticators:
                - App\Security\LoginFormAuthenticator
            form_login:
                login_path: app_login
                check_path: app_login
                enable_csrf: true
            logout:
                path: app_logout

    access_control:
        - { path: ^/administrator, roles: ROLE_ADMIN }
        - { path: ^/veterinarian, roles: ROLE_VETERINARIAN }
        - { path: ^/employee, roles: ROLE_EMPLOYEE }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
