controllers:
  resource:
    path: ../src/Controller/
    namespace: App\Controller
  type: attribute
homepage:
  path: /
  controller: HomeController:index
services:
    path: /services
    controller: ServicesController:index
habitats:
    path: /habitats
    controller: HabitatsController:index
contact:
    path: /contact
    controller: ContactController:index
login:
    path: /login
    controller: LoginController:index
dministrator:
    path: /administrator
    controller: AdministratorController:index
veterinarian:
    path: /veterinarian
    controller: VeterinarianController:index
employee:
    path: /employee
    controller: EmployeeController:index
user:
    path: /user
    controller: UserController:index